/**
 * The one place an icon NAME becomes an icon COMPONENT.
 * ============================================================================
 *
 * WHY THIS EXISTS. 141 files rendered `<Icon icon="mdi:foo">` from
 * `@iconify/react`, which resolves a glyph by FETCHING its set from
 * `api.iconify.design` at runtime. Three consequences, all of them bugs:
 *
 *   1. An operator behind a firewall got pages with no icons at all — and
 *      could not fix it from their own egress rules, because the call is made
 *      by every VISITOR's browser, not by their server.
 *   2. Every one of their customers' browsers contacted a third party the
 *      operator never chose.
 *   3. It was the slow path anyway. Nothing could even START loading until the
 *      bundle had parsed and hydrated; only then a cold DNS + TLS handshake to
 *      an origin that cannot share our HTTP/2 connection, then a re-render. So
 *      every glyph landed after LCP, and `<Button loading>` shipped a spinner
 *      that itself waited on the network to appear.
 *
 * Three files had already reasoned this out in isolation and fixed only
 * themselves — `symbol-explorer.tsx` ("costs an extra round trip to an
 * external CDN"), `kpi/icon.tsx` (its own 198-entry alias table), and
 * `rail-icon.tsx` ("icon sets this app no longer bundles"). This module is
 * those three tables merged, so the next renderer that needs a name resolved
 * does not start a fourth.
 *
 * WHAT IT COSTS. 328 lucide glyphs, ~194KB raw / ~25KB gzip, against the 51KB
 * `@iconify/react` runtime it replaces. The nav chrome resolves names from the
 * menu tables on EVERY page, so this map is in the shared chunk regardless —
 * which is why the other consumers import it rather than keeping private
 * copies. In exchange the glyph is inline SVG in the server-rendered HTML: no
 * request, no pop-in, no layout shift, and it works offline.
 *
 * ADDING A NAME. Put it in `ICONS` below. `pnpm gate:icons` fails the build on
 * any `icon:`/`icon=` string in the tree that this table cannot resolve, which
 * is what stops the drift that produced the original 141-file split.
 */

import type { ComponentType, SVGProps } from "react";
import {
  Activity,
  AlarmClock,
  AlarmClockOff,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Archive,
  AreaChart,
  ArrowDown,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownToLine,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightCircle,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpFromLine,
  ArrowUpRight,
  ArrowUpSquare,
  Award,
  BadgeAlert,
  BadgeCheck,
  BadgePercent,
  Ban,
  Banknote,
  BanknoteArrowDown,
  BanknoteX,
  BarChart,
  BarChart2,
  BarChart3,
  Bell,
  BellRing,
  Bitcoin,
  Blocks,
  Bookmark,
  BookMarked,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Brain,
  BrainCircuit,
  Briefcase,
  Building2,
  Cable,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarX,
  Camera,
  CandlestickChart,
  ChartBar,
  ChartLine,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsUp,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDollarSign,
  CircleDot,
  CirclePause,
  CircleSlash,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  ClockAlert,
  ClockCheck,
  CloudAlert,
  CloudCheck,
  CloudLightning,
  CloudOff,
  CloudUpload,
  Code,
  Code2,
  Coins,
  Compass,
  Component,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  DollarSign,
  DoorClosed,
  Dot,
  Download,
  Droplet,
  Droplets,
  Equal,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileCheck2,
  FileCode,
  FilePen,
  FilePlus,
  FileQuestion,
  Files,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileWarning,
  FileX,
  Filter,
  FilterX,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderOpen,
  Folders,
  FolderSearch,
  GalleryVertical,
  Gauge,
  Gavel,
  Gem,
  Gift,
  GitBranch,
  GitMerge,
  Globe,
  Globe2,
  Grid3x3,
  Hammer,
  Hand,
  HandCoins,
  Handshake,
  HardDrive,
  HardHat,
  Hash,
  Headset,
  Heart,
  HeartPlus,
  HeartPulse,
  HelpCircle,
  Hexagon,
  History,
  Home,
  Hourglass,
  IdCard,
  Image,
  ImageOff,
  ImagePlus,
  Images,
  Inbox,
  Infinity,
  Info,
  Key,
  KeyRound,
  Landmark,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link,
  Link2,
  Link2Off,
  List,
  ListCheck,
  ListChecks,
  ListOrdered,
  ListPlus,
  Loader2,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MailX,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessageCircleMore,
  MessageSquare,
  MessageSquareDashed,
  MessagesSquare,
  Minus,
  MinusCircle,
  Monitor,
  Moon,
  MoreHorizontal,
  MoveHorizontal,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  OctagonAlert,
  OctagonX,
  Package,
  PackageCheck,
  PackageX,
  Palette,
  PanelBottom,
  PanelTop,
  Paperclip,
  Pause,
  PauseCircle,
  PauseOctagon,
  Pencil,
  PenLine,
  Percent,
  Phone,
  PhoneIncoming,
  PhoneOutgoing,
  PieChart,
  PiggyBank,
  Play,
  PlayCircle,
  Plug,
  PlugZap,
  Plus,
  PlusCircle,
  PowerOff,
  Puzzle,
  QrCode,
  Quote,
  Radar,
  Radio,
  RadioTower,
  Receipt,
  ReceiptText,
  RefreshCw,
  RefreshCwOff,
  Repeat,
  Rewind,
  Rocket,
  RotateCcw,
  Route,
  Rss,
  Save,
  Scale,
  ScanFace,
  ScanSearch,
  Scroll,
  ScrollText,
  Search,
  SearchX,
  Send,
  SendHorizontal,
  Server,
  ServerCog,
  Settings,
  Settings2,
  Shapes,
  Share2,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Siren,
  Sliders,
  SlidersHorizontal,
  SlidersVertical,
  Smartphone,
  SmartphoneCharging,
  Snowflake,
  Sparkles,
  Split,
  Sprout,
  Square,
  SquareCheck,
  SquarePen,
  SquarePercent,
  Star,
  StarHalf,
  StarOff,
  StopCircle,
  Store,
  Tag,
  Tags,
  Target,
  TestTube,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  Timer,
  TimerOff,
  ToggleRight,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Trophy,
  Truck,
  Undo2,
  Unlink,
  Unlock,
  Unplug,
  Upload,
  User,
  UserCheck,
  UserCircle,
  UserCog,
  UserMinus,
  UserPlus,
  UserRoundCog,
  Users,
  UsersRound,
  UserX,
  Vault,
  Video,
  Vote,
  Wallet,
  WalletMinimal,
  WandSparkles,
  Waves,
  Waypoints,
  Webhook,
  Weight,
  WifiOff,
  Workflow,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Zap,
} from "lucide-react";
import {
  Discord,
  Facebook,
  Github,
  Instagram,
  Linkedin,
  Twitter,
  Youtube,
} from "@/components/ui/brand-icons";

/**
 * The shape both lucide icons and the vendored brand marks satisfy. The SVG
 * props are part of it because the Iconify call sites this replaces passed
 * `style`, `strokeWidth` and `aria-hidden` straight through to the glyph.
 */
export type IconComponent = ComponentType<
  Omit<SVGProps<SVGSVGElement>, "ref"> & { size?: number | string }
>;

/**
 * Keyed by every shape a stored name actually arrives in: the full Iconify
 * name (`mdi:cash-multiple`), the bare kebab form screens have always written
 * (`credit-card`), and the PascalCase component name that analytics configs
 * use (`TrendingUp`). All three resolve to the same component.
 */
const ICONS: Record<string, IconComponent> = {
  "mdi:check-circle": CheckCircle,
  "lucide:lock": Lock,
  "lucide:check": Check,
  "lucide:triangle-alert": TriangleAlert,
  "mdi:clock-outline": Clock,
  "lucide:layout-dashboard": LayoutDashboard,
  "lucide:refresh-cw": RefreshCw,
  "lucide:settings": Settings,
  "lucide:wallet": Wallet,
  "lucide:circle-alert": CircleAlert,
  "lucide:plus": Plus,
  "lucide:shield-check": ShieldCheck,
  "mdi:percent": Percent,
  "lucide:alert-triangle": AlertTriangle,
  "lucide:users": Users,
  "mdi:alert-circle": AlertCircle,
  "lucide:history": History,
  "lucide:trending-up": TrendingUp,
  "lucide:activity": Activity,
  "lucide:info": Info,
  "lucide:landmark": Landmark,
  "lucide:credit-card": CreditCard,
  "lucide:arrow-left": ArrowLeft,
  "lucide:arrow-left-right": ArrowLeftRight,
  "lucide:tag": Tag,
  "lucide:shield": Shield,
  "lucide:store": Store,
  "lucide:gavel": Gavel,
  "lucide:alert-circle": AlertCircle,
  "lucide:clock": Clock,
  "lucide:coins": Coins,
  "lucide:search": Search,
  "mdi:percent-outline": Percent,
  "lucide:chevron-right": ChevronRight,
  "mdi:calculator": Calculator,
  "lucide:bar-chart-3": BarChart3,
  "mdi:gavel": Gavel,
  "lucide:book-open": BookOpen,
  "lucide:star": Star,
  "lucide:repeat": Repeat,
  "lucide:send": Send,
  "lucide:home": Home,
  "mdi:alert-octagon": AlertOctagon,
  "mdi:trophy": Trophy,
  "mdi:trending-up": TrendingUp,
  "mdi:shield-check": ShieldCheck,
  "mdi:timer-off": TimerOff,
  "lucide:arrow-down-left": ArrowDownLeft,
  "mdi:clock-alert-outline": ClockAlert,
  "lucide:arrow-up-right": ArrowUpRight,
  "lucide:pencil": Pencil,
  "mdi:chart-line": ChartLine,
  "lucide:shield-alert": ShieldAlert,
  "lucide:banknote": Banknote,
  "lucide:arrow-right": ArrowRight,
  "lucide:percent": Percent,
  "lucide:image": Image,
  "lucide:pause": Pause,
  "mdi:clock-alert": ClockAlert,
  "lucide:line-chart": LineChart,
  "lucide:eye": Eye,
  "lucide:candlestick-chart": CandlestickChart,
  "lucide:save": Save,
  "lucide:shopping-bag": ShoppingBag,
  "lucide:zap": Zap,
  "lucide:user": User,
  "lucide:flag": Flag,
  "lucide:file-text": FileText,
  "lucide:megaphone": Megaphone,
  "lucide:package": Package,
  "lucide:scroll-text": ScrollText,
  "mdi:snowflake": Snowflake,
  "lucide:circle-check": CircleCheck,
  "lucide:badge-check": BadgeCheck,
  "lucide:trash-2": Trash2,
  "lucide:bot": Bot,
  "lucide:loader-2": Loader2,
  "lucide:blocks": Blocks,
  "mdi:play-circle": PlayCircle,
  "lucide:external-link": ExternalLink,
  "lucide:file-question": FileQuestion,
  "lucide:list": List,
  "lucide:notebook-pen": NotebookPen,
  "lucide:link": Link,
  "lucide:puzzle": Puzzle,
  "lucide:calendar-clock": CalendarClock,
  "lucide:check-circle-2": CheckCircle2,
  "mdi:bitcoin": Bitcoin,
  "lucide:eye-off": EyeOff,
  "lucide:user-check": UserCheck,
  "lucide:message-square": MessageSquare,
  "lucide:inbox": Inbox,
  "lucide:hand-coins": HandCoins,
  "lucide:scale": Scale,
  "lucide:play": Play,
  "lucide:messages-square": MessagesSquare,
  "lucide:mail": Mail,
  "lucide:trophy": Trophy,
  "lucide:copy": Copy,
  "lucide:cloud-off": CloudOff,
  "lucide:smartphone": Smartphone,
  "lucide:route": Route,
  "lucide:receipt-text": ReceiptText,
  "lucide:loader-circle": LoaderCircle,
  "lucide:rocket": Rocket,
  "lucide:timer": Timer,
  "lucide:gift": Gift,
  "lucide:hourglass": Hourglass,
  "lucide:radio": Radio,
  "lucide:sparkles": Sparkles,
  "mdi:pause-circle": PauseCircle,
  "lucide:handshake": Handshake,
  "lucide:circle-x": CircleX,
  "lucide:dot": Dot,
  "lucide:key-round": KeyRound,
  "lucide:grid-3x3": Grid3x3,
  "lucide:newspaper": Newspaper,
  "lucide:arrow-down-to-line": ArrowDownToLine,
  "mdi:trending-down": TrendingDown,
  "lucide:file-pen": FilePen,
  "lucide:search-x": SearchX,
  "lucide:layers": Layers,
  "lucide:send-horizontal": SendHorizontal,
  "lucide:minus": Minus,
  "lucide:receipt": Receipt,
  "lucide:gauge": Gauge,
  "lucide:chevron-down": ChevronDown,
  "lucide:help-circle": HelpCircle,
  "lucide:sliders-horizontal": SlidersHorizontal,
  "lucide:circle-pause": CirclePause,
  "lucide:globe": Globe,
  "lucide:paperclip": Paperclip,
  "lucide:crown": Crown,
  "mdi:search": Search,
  "ph:chart-line-duotone": ChartLine,
  "lucide:message-square-dashed": MessageSquareDashed,
  "akar-icons:arrow-left": ArrowLeft,
  "lucide:chevron-left": ChevronLeft,
  "uim:star": Star,
  "ph:shield-check-duotone": ShieldCheck,
  "ph:seal-check-duotone": BadgeCheck,
  "lucide:list-ordered": ListOrdered,
  "mdi:receipt-text": ReceiptText,
  "mdi:shield-off": ShieldOff,
  "lucide:x-circle": XCircle,
  "lucide:user-plus": UserPlus,
  "mdi:image": Image,
  "lucide:split": Split,
  "ph:copy-duotone": Copy,
  "lucide:wand-sparkles": WandSparkles,
  "lucide:arrow-right-circle": ArrowRightCircle,
  "lucide:arrow-down": ArrowDown,
  "lucide:arrow-up-circle": ArrowUpCircle,
  "lucide:moon": Moon,
  "lucide:alarm-clock": AlarmClock,
  "lucide:filter": Filter,
  "lucide:brain-circuit": BrainCircuit,
  "mdi:lock": Lock,
  "solar:clipboard-list-bold-duotone": ClipboardList,
  "mdi:eye": Eye,
  "lucide:workflow": Workflow,
  "mdi:radar": Radar,
  "lucide:trending-down": TrendingDown,
  "lucide:arrow-down-circle": ArrowDownCircle,
  "lucide:snowflake": Snowflake,
  "mdi:clock": Clock,
  "lucide:users-round": UsersRound,
  "lucide:clipboard-list": ClipboardList,
  "lucide:layout-grid": LayoutGrid,
  "lucide:file-x": FileX,
  "mdi:eye-off-outline": EyeOff,
  "ph:user-circle": UserCircle,
  "lucide:undo-2": Undo2,
  "lucide:hand": Hand,
  "solar:settings-bold-duotone": Settings,
  "lucide:refresh-cw-off": RefreshCwOff,
  "lucide:plug": Plug,
  "ph:lock-duotone": Lock,
  "lucide:download": Download,
  "lucide:globe-2": Globe2,
  "mdi:star": Star,
  "lucide:server-cog": ServerCog,
  "mdi:stop-circle": StopCircle,
  "mdi:pause-octagon": PauseOctagon,
  "lucide:ban": Ban,
  "lucide:palette": Palette,
  "lucide:waypoints": Waypoints,
  "mdi:wallet": Wallet,
  "lucide:truck": Truck,
  "ph:user-circle-duotone": UserCircle,
  "lucide:arrow-up-from-line": ArrowUpFromLine,
  "lucide:git-branch": GitBranch,
  "mdi:plus": Plus,
  "lucide:message-circle": MessageCircle,
  "ph:credit-card-duotone": CreditCard,
  "ph:scroll-duotone": Scroll,
  "lucide:circle-dashed": CircleDashed,
  "lucide:webhook": Webhook,
  "solar:folder-line-duotone": Folder,
  "lucide:quote": Quote,
  "lucide:cloud-check": CloudCheck,
  "lucide:building-2": Building2,
  "mdi:timer-outline": Timer,
  "ph:headset-duotone": Headset,
  "lucide:brain": Brain,
  "lucide:wifi-off": WifiOff,
  "lucide:filter-x": FilterX,
  "lucide:briefcase": Briefcase,
  "lucide:calendar-days": CalendarDays,
  "ph:wallet-duotone": Wallet,
  "lucide:image-off": ImageOff,
  "lucide:plug-zap": PlugZap,
  "lucide:timer-off": TimerOff,
  "lucide:flame": Flame,
  "lucide:hard-drive": HardDrive,
  "lucide:share-2": Share2,
  "mdi:door-closed": DoorClosed,
  "lucide:arrow-up": ArrowUp,
  "lucide:list-checks": ListChecks,
  "lucide:droplet": Droplet,
  "mdi:brain": Brain,
  "lucide:heart-pulse": HeartPulse,
  "lucide:upload": Upload,
  "lucide:radio-tower": RadioTower,
  "ph:globe-duotone": Globe,
  "mdi:waves": Waves,
  "lucide:folder": Folder,
  "mdi:circle-outline": Circle,
  "mdi:database": Database,
  "ph:database-duotone": Database,
  "ph:floppy-disk-duotone": Save,
  "ph:hard-drives-duotone": HardDrive,
  "lucide:bar-chart-2": BarChart2,
  "lucide:layout": Layout,
  "mdi:minus-circle-outline": MinusCircle,
  "lucide:star-off": StarOff,
  "lucide:target": Target,
  "lucide:heart": Heart,
  "lucide:library": Library,
  "lucide:file-search": FileSearch,
  "lucide:toggle-right": ToggleRight,
  "ph:image-duotone": Image,
  "ph:monitor-duotone": Monitor,
  "lucide:euro": Euro,
  "mdi:download": Download,
  "lucide:boxes": Boxes,
  "lucide:vault": Vault,
  "mdi:ticket-outline": Ticket,
  "lucide:folder-open": FolderOpen,
  "lucide:cpu": Cpu,
  "akar-icons:chevron-right": ChevronRight,
  "lucide:unplug": Unplug,
  "lucide:user-round-cog": UserRoundCog,
  "solar:palette-bold-duotone": Palette,
  "lucide:medal": Medal,
  "ph:user-circle-light": UserCircle,
  "mdi:shield-check-outline": ShieldCheck,
  "lucide:video": Video,
  "ph:users-duotone": Users,
  "ph:download-duotone": Download,
  "ph:chart-bar-duotone": ChartBar,
  "lucide:pie-chart": PieChart,
  "mdi:shield-alert": ShieldAlert,
  "ph:images-duotone": Images,
  "lucide:code": Code,
  "lucide:camera": Camera,
  "mdi:calendar": Calendar,
  "mdi:check": Check,
  "lucide:chevron-up": ChevronUp,
  "lucide:alarm-clock-off": AlarmClockOff,
  "mdi:medal": Medal,
  "lucide:file-code": FileCode,
  "mdi:alert-circle-outline": AlertCircle,
  "lucide:log-in": LogIn,
  "mdi:help-circle": HelpCircle,
  "line-md:play": Play,
  "lucide:circle-dot": CircleDot,
  "mdi:test-tube": TestTube,
  "mdi:weight": Weight,
  "ph:hourglass-duotone": Hourglass,
  "mdi:file-outline": File,
  "solar:list-check-bold-duotone": ListCheck,
  // The Reported Content queue in `config/menu.ts`. Mapped by MEANING to the
  // same glyph `lucide:flag` already resolves to — a flag is a flag, and the
  // registry deliberately answers both names rather than making the menu
  // rename an icon it borrowed from another set.
  "solar:flag-bold-duotone": Flag,
  "lucide:droplets": Droplets,
  "lucide:unlock": Unlock,
  "lucide:rotate-ccw": RotateCcw,
  "lucide:shopping-cart": ShoppingCart,
  "mdi:timer": Timer,
  "lucide:scan-face": ScanFace,
  "lucide:circle-dollar-sign": CircleDollarSign,
  "lucide:file-spreadsheet": FileSpreadsheet,
  "mdi:target": Target,
  "lucide:qr-code": QrCode,
  "ph:handshake-duotone": Handshake,
  "lucide:power-off": PowerOff,
  "lucide:sprout": Sprout,
  "lucide:arrow-right-left": ArrowRightLeft,
  "mdi:check-circle-outline": CheckCircle,
  "lucide:vote": Vote,
  "mdi:cloud-alert": CloudAlert,
  "lucide:thumbs-up": ThumbsUp,
  "lucide:award": Award,
  "uim:star-half-alt": StarHalf,
  "mdi:handshake": Handshake,
  "lucide:flask-conical": FlaskConical,
  "lucide:scan-search": ScanSearch,
  "mdi:leaf": Leaf,
  "ph:newspaper-duotone": Newspaper,
  "ph:rss-duotone": Rss,
  "lucide:bell-ring": BellRing,
  "lucide:dollar-sign": DollarSign,
  "mdi:lock-outline": Lock,
  "mdi:cookie": Cookie,
  "lucide:database": Database,
  "mdi:file-plus-outline": FilePlus,
  "mdi:home": Home,
  "lucide:link-2": Link2,
  "lucide:hard-hat": HardHat,
  "lucide:book-marked": BookMarked,
  "lucide:chevrons-up-down": ChevronsUpDown,
  "lucide:list-plus": ListPlus,
  "mdi:history": History,
  "mdi:heart-plus": HeartPlus,
  "mdi:key": Key,
  "mdi:layers": Layers,
  "lucide:settings-2": Settings2,
  "lucide:tags": Tags,
  "ph:key-duotone": Key,
  "lucide:mail-check": MailCheck,
  "lucide:layout-template": LayoutTemplate,
  "mdi:medal-outline": Medal,
  "mdi:hammer": Hammer,
  "solar:wallet-bold-duotone": Wallet,
  "lucide:clipboard-check": ClipboardCheck,
  "mdi:gift": Gift,
  "ph:coins-duotone": Coins,
  "lucide:hash": Hash,
  "lucide:move-horizontal": MoveHorizontal,
  "lucide:bell": Bell,
  "solar:code-bold-duotone": Code,
  "lucide:compass": Compass,
  "ph:calendar-duotone": Calendar,
  "lucide:lightbulb": Lightbulb,
  "mdi:tag": Tag,
  "mdi:calendar-check": CalendarCheck,
  "mdi:wallet-outline": Wallet,
  "lucide:folder-search": FolderSearch,
  "lucide:notebook": Notebook,
  "ph:book-open-duotone": BookOpen,
  "ph:briefcase-duotone": Briefcase,
  "mdi:star-outline": Star,
  "mdi:image-off-outline": ImageOff,
  "lucide:calculator": Calculator,
  "mdi:shield-alert-outline": ShieldAlert,
  "lucide:file-check-2": FileCheck2,
  "lucide:file-check": FileCheck,
  "lucide:siren": Siren,
  "mdi:arrow-left": ArrowLeft,
  "lucide:chart-line": ChartLine,
  "mdi:cpu": Cpu,
  "lucide:pause-circle": PauseCircle,
  "lucide:rewind": Rewind,
  "lucide:user-x": UserX,
  "mdi:infinity": Infinity,
  "mdi:gift-outline": Gift,
  "lucide:lock-keyhole": LockKeyhole,
  "mdi:calendar-clock": CalendarClock,
  "mdi:truck": Truck,
  "lucide:octagon-alert": OctagonAlert,
  "fa-solid:external-link-alt": ExternalLink,
  "akar-icons:chevron-left": ChevronLeft,
  "lucide:cloud-lightning": CloudLightning,
  "ph:brain-duotone": Brain,
  "lucide:calendar": Calendar,
  "lucide:network": Network,
  "lucide:git-merge": GitMerge,
  "ph:bell-duotone": Bell,
  "mdi:handshake-outline": Handshake,
  "line-md:pause": Pause,
  "mdi:link": Link,
  "lucide:file-warning": FileWarning,
  "lucide:fingerprint": Fingerprint,
  "lucide:pen-line": PenLine,
  "lucide:code-2": Code2,
  "mdi:tag-outline": Tag,
  "lucide:life-buoy": LifeBuoy,
  "ph:megaphone-duotone": Megaphone,
  "mdi:image-plus": ImagePlus,
  "lucide:check-check": CheckCheck,
  "ph:shopping-cart-duotone": ShoppingCart,
  "lucide:smartphone-charging": SmartphoneCharging,
  "lucide:check-circle": CheckCircle,
  "mdi:clock-check-outline": ClockCheck,
  "mdi:rocket": Rocket,
  "lucide:plus-circle": PlusCircle,
  "lucide:banknote-arrow-down": BanknoteArrowDown,
  "lucide:circle-slash": CircleSlash,
  "mdi:close-circle": XCircle,
  "mdi:cancel": Ban,
  "mdi:timer-sand": Hourglass,
  "mdi:cash-multiple": Banknote,
  "mdi:cash-plus": ArrowUpCircle,
  "mdi:cash-refund": Undo2,
  "mdi:currency-usd": DollarSign,
  "mdi:cash-check": BadgeCheck,
  "mdi:cash-lock": Lock,
  "mdi:account-group": Users,
  "mdi:ethereum": Diamond,
  "mdi:thumb-down": ThumbsDown,
  "mdi:progress-clock": Hourglass,
  "mdi:account-check": UserCheck,
  "mdi:scale-balance": Scale,
  "mdi:cash-minus": ArrowDownCircle,
  "mdi:timer-alert": AlertCircle,
  "mdi:account-cancel": UserX,
  "mdi:cash-fast": Zap,
  "mdi:account-multiple": Users,
  "mdi:account-star": Award,
  "mdi:speedometer": Gauge,
  "mdi:account-cash": Banknote,
  "mdi:sync": RefreshCw,
  "mdi:cash": Banknote,
  "mdi:check-all": ListChecks,
  "mdi:account-multiple-check": UsersRound,
  "mdi:swap-horizontal-bold": ArrowLeftRight,
  "mdi:cart-check": PackageCheck,
  "mdi:bank-transfer-out": ArrowUpFromLine,
  "mdi:gesture-tap": Sparkles,
  "mdi:account-tie": Users,
  "mdi:truck-fast": Truck,
  "mdi:tune": Sliders,
  "mdi:swap-vertical": ArrowUpDown,
  "mdi:star-circle": Star,
  "mdi:bank-transfer-in": ArrowDownToLine,
  "mdi:tag-multiple": Tags,
  "mdi:storefront": Store,
  "mdi:chart-timeline-variant": LineChart,
  "mdi:clock-fast": Zap,
  "mdi:shield-search": ShieldAlert,
  "mdi:star-half-full": Star,
  "mdi:file-document-edit-outline": FileText,
  "mdi:currency-btc": Bitcoin,
  "mdi:account-pause": Pause,
  "mdi:account-clock": Clock,
  "mdi:transfer": ArrowLeftRight,
  "mdi:view-grid": Grid3x3,
  "mdi:finance": TrendingUp,
  "mdi:cube-outline": Box,
  "mdi:arrow-up-bold-circle": ArrowUpCircle,
  "mdi:package-variant-remove": PackageX,
  "mdi:format-list-checks": ListChecks,
  "mdi:robot": Bot,
  "mdi:package-variant": Package,
  "mdi:calendar-month": CalendarDays,
  "mdi:account": User,
  "mdi:tag-check": BadgeCheck,
  "mdi:package-variant-closed": Package,
  "mdi:account-question": User,
  "mdi:fire": Flame,
  "mdi:update": RefreshCw,
  "mdi:file-document-outline": FileText,
  "line-md:close": XCircle,
  "mdi:wallet-plus": WalletMinimal,
  "mdi:email-multiple": Mail,
  "mdi:counter": Hash,
  "mdi:format-list-bulleted": List,
  "mdi:calendar-end": CalendarClock,
  "mdi:bank-plus": PiggyBank,
  "mdi:account-arrow-right": ArrowUpFromLine,
  "mdi:account-remove": UserMinus,
  "mdi:heart-multiple": Heart,
  "mdi:shopping": ShoppingCart,
  "mdi:chart-bell-curve": Activity,
  "mdi:information-outline": AlertCircle,
  "mdi:swap-horizontal": ArrowLeftRight,
  "mdi:message-alert": AlertCircle,
  "mdi:calendar-today": CalendarDays,
  "mdi:alert-outline": AlertTriangle,
  "carbon:close": XCircle,
  "mdi:chart-areaspline": AreaChart,
  "mdi:comment-multiple": MessageSquare,
  "mdi:new-box": Sparkles,
  "mdi:information": AlertCircle,
  "mdi:comment-text-multiple": MessageSquare,
  "mdi:close-thick": XCircle,
  "mdi:truck-delivery": Truck,
  "mdi:cash-clock": Clock,
  "mdi:book-open-variant": BookOpen,
  "mdi:close-octagon": XOctagon,
  "mdi:cash-remove": BanknoteX,
  "mdi:twitter": Twitter,
  "mdi:github": Github,
  "lucide:github": Github,
  "solar:chart-2-bold-duotone": BarChart3,
  "ph:gear-duotone": Settings,
  "ph:arrows-left-right-duotone": ArrowLeftRight,
  "mdi:chart-donut": PieChart,
  "mdi:lock-clock": Lock,
  "mdi:timer-alert-outline": AlertCircle,
  "mdi:alert-decagram": BadgeAlert,
  "mdi:swap-vertical-bold": ArrowUpDown,
  "ph:image-square-duotone": Image,
  "solar:bag-smile-bold-duotone": ShoppingBag,
  "mdi:hexagon-multiple": Hexagon,
  "material-symbols:arrow-back": ArrowLeft,
  "mdi:arrow-collapse-down": ArrowDownToLine,
  "ph:bell-ringing-duotone": BellRing,
  "mdi:arrow-top-right": ArrowUpRight,
  "mdi:timeline-clock": History,
  "mdi:exit-run": LogOut,
  "mdi:email-outline": Mail,
  "mdi:arrow-expand-horizontal": MoveHorizontal,
  "ph:users-four-duotone": Users,
  "ri:exchange-2-line": ArrowLeftRight,
  "mdi:facebook": Facebook,
  "mdi:ticket-confirmation": TicketCheck,
  "mdi:link-variant-off": Unlink,
  "mdi:chart-box-outline": BarChart3,
  "lucide:api": Webhook,
  "tabler:binary-tree": Network,
  "mdi:support": LifeBuoy,
  "mdi:folder-multiple": Folders,
  "mdi:safe": Vault,
  "ph:bank-duotone": Landmark,
  "ph:certificate-duotone": Award,
  "ph:download-simple-duotone": Download,
  "mdi:clock-time-four-outline": Clock,
  "mdi:lock-alert": ShieldAlert,
  "hugeicons:ico": Coins,
  "carbon:checkmark": CheckCircle,
  "mdi:account-heart": Heart,
  "ph:scales-duotone": Scale,
  "mdi:head-question": HelpCircle,
  "ph:question-duotone": HelpCircle,
  "mdi:playlist-plus": ListPlus,
  "mdi:close-circle-outline": XCircle,
  "mdi:currency-usd-off": BanknoteX,
  "mdi:hand-back-left-off": Ban,
  "mdi:bank-outline": Landmark,
  "mdi:magnify": Search,
  "ph:robot-duotone": Bot,
  "ph:chart-line-up-duotone": TrendingUp,
  "lucide:discord": Discord,
  "ph:plugs-connected-duotone": Cable,
  "mdi:link-off": Link2Off,
  "lucide:youtube": Youtube,
  "lucide:twitter": Twitter,
  "mdi:cash-sync": RefreshCw,
  "solar:document-line-duotone": FileText,
  "solar:planet-2-bold-duotone": Globe,
  "mdi:shield-star": ShieldCheck,
  "mdi:timeline-clock-outline": History,
  "ph:storefront-duotone": Store,
  "heroicons:chevron-right-20-solid": ChevronRight,
  "mdi:inbox-arrow-down": Inbox,
  "mdi:sale": BadgePercent,
  "ph:hand-withdraw-duotone": HandCoins,
  "mdi:archive-check-outline": Archive,
  "mdi:store-check-outline": Store,
  "mdi:pencil-plus-outline": SquarePen,
  "humbleicons:exchange-vertical": ArrowUpDown,
  "mdi:briefcase-clock": Briefcase,
  "ph:stack-duotone": Layers,
  "mdi:archive-clock-outline": Archive,
  "solar:document-text-bold-duotone": FileText,
  "mdi:undo-variant": Undo2,
  "ph:currency-btc-duotone": Bitcoin,
  "solar:users-group-two-rounded-bold-duotone": UsersRound,
  "solar:document-add-bold-duotone": FilePlus,
  "mdi:content-copy": Copy,
  "bi:currency-exchange": ArrowLeftRight,
  "solar:dollar-minimalistic-line-duotone": DollarSign,
  "mdi:instagram": Instagram,
  "ph:upload-simple-duotone": Upload,
  "mdi:wallet-bifold": Wallet,
  "ph:chat-circle-duotone": MessageCircle,
  "mdi:lock-open-check": LockOpen,
  "ph:envelope-duotone": Mail,
  "mdi:text-box-remove-outline": FileX,
  "mdi:file-remove-outline": FileX,
  "ph:chat-circle-text-duotone": MessageCircleMore,
  "mdi:arrow-up-bold-box-outline": ArrowUpSquare,
  "mdi:close-octagon-outline": OctagonX,
  "mdi:refresh": RefreshCw,
  "solar:transfer-vertical-line-duotone": ArrowUpDown,
  "ph:ranking-duotone": Trophy,
  "arcticons:samsung-finder": Search,
  "mdi:alert-octagram": AlertOctagon,
  "solar:course-up-bold-duotone": TrendingUp,
  "ph:globe-hemisphere-west-duotone": Globe,
  "mdi:package-variant-closed-remove": PackageX,
  "mdi:cash-register": Banknote,
  "mdi:calendar-alert": CalendarClock,
  "mdi:calendar-remove": CalendarX,
  "mdi:check-decagram": BadgeCheck,
  "mdi:timer-check": ClockCheck,
  "mdi:linkedin": Linkedin,
  "carbon:api": Code,
  "lucide:linkedin": Linkedin,
  "mdi:bank": Landmark,
  "ph:puzzle-piece-duotone": Puzzle,
  "mdi:chart-line-variant": LineChart,
  "mdi:web": Globe,
  "mdi:loading": LoaderCircle,
  "solar:course-up-line-duotone": TrendingUp,
  "mdi:arrow-expand-up": ArrowUpFromLine,
  "solar:dollar-minimalistic-bold-duotone": DollarSign,
  "mdi:file-document-multiple-outline": Files,
  "lucide:instagram": Instagram,
  "ri:secure-payment-line": CreditCard,
  "ph:currency-dollar-duotone": DollarSign,
  "mdi:calculator-variant-outline": Calculator,
  "lucide:layout-top": PanelTop,
  "ph:currency-circle-dollar-duotone": CircleDollarSign,
  "solar:posts-carousel-vertical-bold-duotone": GalleryVertical,
  "solar:home-angle-line-duotone": Home,
  "solar:transfer-horizontal-bold-duotone": ArrowLeftRight,
  "solar:slider-vertical-bold-duotone": SlidersVertical,
  "mdi:file-lock-open-outline": LockOpen,
  "mdi:storefront-check": BadgeCheck,
  "mdi:percent-box-outline": SquarePercent,
  "mdi:account-off": UserX,
  "mdi:tray-full": Inbox,
  "ph:currency-dollar-simple-duotone": DollarSign,
  "mdi:thumb-down-outline": ThumbsDown,
  "mdi:lightning-bolt": Zap,
  "solar:pallete-2-bold-duotone": Palette,
  "mdi:stop": Square,
  "fluent:content-view-28-regular": LayoutGrid,
  "mdi:snowflake-alert": Snowflake,
  "mdi:arrow-down-bold-circle": ArrowDownCircle,
  "solar:widget-4-bold-duotone": LayoutDashboard,
  "mdi:file-document-plus-outline": FilePlus,
  "mdi:close-network": Unplug,
  "ph:identification-card-duotone": IdCard,
  "mdi:trophy-variant": Trophy,
  "mdi:sleep": Moon,
  "mdi:link-variant": Link,
  "mdi:briefcase-exchange-outline": Briefcase,
  "mdi:progress-alert": AlertCircle,
  "mdi:account-off-outline": UserX,
  "lucide:layout-bottom": PanelBottom,
  "lucide:sitemap": Network,

  // Bare kebab + PascalCase aliases for the same components.
  "CheckCircle2": CheckCircle2,
  "WalletMinimal": WalletMinimal,
  "Banknote": Banknote,
  "ArrowUpCircle": ArrowUpCircle,
  "CheckCircle": CheckCircle,
  "stop-circle": StopCircle,
  "ArrowUp": ArrowUp,
  "play-circle": PlayCircle,
  "Archive": Archive,
  "Square": Square,
  "chevron-up": ChevronUp,
  "Scroll": Scroll,
  "RotateCcw": RotateCcw,
  "layout-template": LayoutTemplate,
  "star-off": StarOff,
  "Play": Play,
  "test-tube": TestTube,
  "Sparkles": Sparkles,
  "HeartPlus": HeartPlus,
  "Leaf": Leaf,
  "Store": Store,
  "alert-octagon": AlertOctagon,
  "ArrowUpDown": ArrowUpDown,
  "Star": Star,
  "circle-dot": CircleDot,
  "ClockAlert": ClockAlert,
  "bar-chart3": BarChart3,
  "trending-down": TrendingDown,
  "log-in": LogIn,
  "notebook-pen": NotebookPen,
  "LogOut": LogOut,
  "Minus": Minus,
  "circle-dollar-sign": CircleDollarSign,
  "Link": Link,
  "Bitcoin": Bitcoin,
  "PenLine": PenLine,
  "plus-circle": PlusCircle,
  "Check": Check,
  "list-check": ListCheck,
  "Upload": Upload,
  "Globe": Globe,
  "Ticket": Ticket,
  "Download": Download,
  "user-round-cog": UserRoundCog,
  "mail-check": MailCheck,
  "life-buoy": LifeBuoy,
  "Calculator": Calculator,
  "BadgePercent": BadgePercent,
  "send-horizontal": SendHorizontal,
  "circle-pause": CirclePause,
  "LogIn": LogIn,
  "octagon-x": OctagonX,
  "TestTube": TestTube,
  "Fingerprint": Fingerprint,
  "LayoutTemplate": LayoutTemplate,
  "ChevronLeft": ChevronLeft,
  "Code2": Code2,
  "Key": Key,
  "SlidersVertical": SlidersVertical,
  "FileWarning": FileWarning,
  "BarChart3": BarChart3,
  "CalendarCheck": CalendarCheck,
  "ArrowDownCircle": ArrowDownCircle,
  "folder-open": FolderOpen,
  "Webhook": Webhook,
  "ticket-check": TicketCheck,
  "HardHat": HardHat,
  "LifeBuoy": LifeBuoy,
  "arrow-down-left": ArrowDownLeft,
  "TimerOff": TimerOff,
  "user-circle": UserCircle,
  "UserRoundCog": UserRoundCog,
  "image-plus": ImagePlus,
  "PlugZap": PlugZap,
  "Library": Library,
  "Cable": Cable,
  "Quote": Quote,
  "eye-off": EyeOff,
  "check-circle": CheckCircle,
  "IdCard": IdCard,
  "id-card": IdCard,
  "ChevronsUpDown": ChevronsUpDown,
  "message-circle-more": MessageCircleMore,
  "RefreshCwOff": RefreshCwOff,
  "Box": Box,
  "ArrowDown": ArrowDown,
  "file-pen": FilePen,
  "CreditCard": CreditCard,
  "circle-dashed": CircleDashed,
  "BarChart2": BarChart2,
  "Filter": Filter,
  "FileX": FileX,
  "x-circle": XCircle,
  "Plus": Plus,
  "MinusCircle": MinusCircle,
  "Snowflake": Snowflake,
  "Target": Target,
  "ArrowUpRight": ArrowUpRight,
  "radio-tower": RadioTower,
  "LoaderCircle": LoaderCircle,
  "arrow-up-right": ArrowUpRight,
  "file-code": FileCode,
  "trending-up": TrendingUp,
  "Clock": Clock,
  "qr-code": QrCode,
  "Settings": Settings,
  "file-x": FileX,
  "ArrowRight": ArrowRight,
  "star-half": StarHalf,
  "Mail": Mail,
  "Linkedin": Linkedin,
  "pause-circle": PauseCircle,
  "PanelBottom": PanelBottom,
  "BanknoteArrowDown": BanknoteArrowDown,
  "CloudAlert": CloudAlert,
  "Monitor": Monitor,
  "square-percent": SquarePercent,
  "panel-bottom": PanelBottom,
  "link2-off": Link2Off,
  "QrCode": QrCode,
  "ListChecks": ListChecks,
  "Image": Image,
  "users-round": UsersRound,
  "HelpCircle": HelpCircle,
  "XOctagon": XOctagon,
  "toggle-right": ToggleRight,
  "chevron-down": ChevronDown,
  "ChevronRight": ChevronRight,
  "Layers": Layers,
  "wifi-off": WifiOff,
  "arrow-right-circle": ArrowRightCircle,
  "calendar-days": CalendarDays,
  "Code": Code,
  "DoorClosed": DoorClosed,
  "arrow-up-from-line": ArrowUpFromLine,
  "alert-circle": AlertCircle,
  "XCircle": XCircle,
  "FileCheck2": FileCheck2,
  "shopping-bag": ShoppingBag,
  "Smartphone": Smartphone,
  "Youtube": Youtube,
  "timer-off": TimerOff,
  "triangle-alert": TriangleAlert,
  "Lock": Lock,
  "log-out": LogOut,
  "History": History,
  "server-cog": ServerCog,
  "Trash2": Trash2,
  "Newspaper": Newspaper,
  "FileSpreadsheet": FileSpreadsheet,
  "octagon-alert": OctagonAlert,
  "CandlestickChart": CandlestickChart,
  "user-check": UserCheck,
  "ImageOff": ImageOff,
  "Workflow": Workflow,
  "badge-percent": BadgePercent,
  "Link2": Link2,
  "receipt-text": ReceiptText,
  "lock-keyhole": LockKeyhole,
  "Zap": Zap,
  "bar-chart2": BarChart2,
  "arrow-up-square": ArrowUpSquare,
  "WandSparkles": WandSparkles,
  "SendHorizontal": SendHorizontal,
  "ListPlus": ListPlus,
  "Copy": Copy,
  "OctagonAlert": OctagonAlert,
  "StarOff": StarOff,
  "shield-off": ShieldOff,
  "Heart": Heart,
  "square-pen": SquarePen,
  "BookOpen": BookOpen,
  "ClipboardList": ClipboardList,
  "message-square-dashed": MessageSquareDashed,
  "WifiOff": WifiOff,
  "TicketCheck": TicketCheck,
  "move-horizontal": MoveHorizontal,
  "PlusCircle": PlusCircle,
  "SquarePercent": SquarePercent,
  "PackageX": PackageX,
  "MessageCircle": MessageCircle,
  "chart-bar": ChartBar,
  "Send": Send,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-up-circle": ArrowUpCircle,
  "UserCheck": UserCheck,
  "calendar-check": CalendarCheck,
  "Medal": Medal,
  "Boxes": Boxes,
  "git-branch": GitBranch,
  "file-search": FileSearch,
  "AlertCircle": AlertCircle,
  "file-plus": FilePlus,
  "arrow-right-left": ArrowRightLeft,
  "NotebookPen": NotebookPen,
  "Diamond": Diamond,
  "UserX": UserX,
  "pause-octagon": PauseOctagon,
  "Eye": Eye,
  "shield-alert": ShieldAlert,
  "dollar-sign": DollarSign,
  "Shield": Shield,
  "AlarmClockOff": AlarmClockOff,
  "ShoppingBag": ShoppingBag,
  "EyeOff": EyeOff,
  "ShieldAlert": ShieldAlert,
  "power-off": PowerOff,
  "Waves": Waves,
  "banknote-arrow-down": BanknoteArrowDown,
  "Notebook": Notebook,
  "Briefcase": Briefcase,
  "ChevronDown": ChevronDown,
  "Camera": Camera,
  "sliders-horizontal": SlidersHorizontal,
  "UserCircle": UserCircle,
  "BadgeCheck": BadgeCheck,
  "Radar": Radar,
  "Bell": Bell,
  "Unlock": Unlock,
  "ArrowLeft": ArrowLeft,
  "Repeat": Repeat,
  "cloud-lightning": CloudLightning,
  "ServerCog": ServerCog,
  "circle-x": CircleX,
  "Tags": Tags,
  "banknote-x": BanknoteX,
  "Route": Route,
  "ShoppingCart": ShoppingCart,
  "alert-triangle": AlertTriangle,
  "Plug": Plug,
  "Hexagon": Hexagon,
  "clock-check": ClockCheck,
  "BellRing": BellRing,
  "StarHalf": StarHalf,
  "SquarePen": SquarePen,
  "Handshake": Handshake,
  "thumbs-down": ThumbsDown,
  "message-circle": MessageCircle,
  "Hourglass": Hourglass,
  "StopCircle": StopCircle,
  "ChartLine": ChartLine,
  "door-closed": DoorClosed,
  "heart-pulse": HeartPulse,
  "PieChart": PieChart,
  "pen-line": PenLine,
  "Infinity": Infinity,
  "CircleX": CircleX,
  "CalendarDays": CalendarDays,
  "book-marked": BookMarked,
  "package-check": PackageCheck,
  "Crown": Crown,
  "Brain": Brain,
  "gallery-vertical": GalleryVertical,
  "Search": Search,
  "Coins": Coins,
  "Info": Info,
  "CloudLightning": CloudLightning,
  "BadgeAlert": BadgeAlert,
  "Home": Home,
  "chevron-left": ChevronLeft,
  "FileSearch": FileSearch,
  "ReceiptText": ReceiptText,
  "GitMerge": GitMerge,
  "HeartPulse": HeartPulse,
  "Droplet": Droplet,
  "MessageSquare": MessageSquare,
  "KeyRound": KeyRound,
  "circle-slash": CircleSlash,
  "package-x": PackageX,
  "Rocket": Rocket,
  "Flame": Flame,
  "Hammer": Hammer,
  "Flag": Flag,
  "file-check2": FileCheck2,
  "arrow-down-to-line": ArrowDownToLine,
  "Ban": Ban,
  "Rewind": Rewind,
  "scan-search": ScanSearch,
  "Blocks": Blocks,
  "Save": Save,
  "search-x": SearchX,
  "Receipt": Receipt,
  "Folder": Folder,
  "GalleryVertical": GalleryVertical,
  "lock-open": LockOpen,
  "RefreshCw": RefreshCw,
  "wand-sparkles": WandSparkles,
  "book-open": BookOpen,
  "layout-grid": LayoutGrid,
  "Puzzle": Puzzle,
  "UserPlus": UserPlus,
  "Settings2": Settings2,
  "Radio": Radio,
  "File": File,
  "git-merge": GitMerge,
  "Lightbulb": Lightbulb,
  "FilePen": FilePen,
  "hard-drive": HardDrive,
  "ShieldCheck": ShieldCheck,
  "arrow-up": ArrowUp,
  "calendar-clock": CalendarClock,
  "cloud-alert": CloudAlert,
  "file-text": FileText,
  "PauseCircle": PauseCircle,
  "OctagonX": OctagonX,
  "shield-check": ShieldCheck,
  "piggy-bank": PiggyBank,
  "cloud-check": CloudCheck,
  "HardDrive": HardDrive,
  "Truck": Truck,
  "MessageSquareDashed": MessageSquareDashed,
  "Package": Package,
  "badge-check": BadgeCheck,
  "file-question": FileQuestion,
  "CircleDashed": CircleDashed,
  "bell-ring": BellRing,
  "rotate-ccw": RotateCcw,
  "List": List,
  "PauseOctagon": PauseOctagon,
  "panel-top": PanelTop,
  "calendar-x": CalendarX,
  "Percent": Percent,
  "candlestick-chart": CandlestickChart,
  "PiggyBank": PiggyBank,
  "AreaChart": AreaChart,
  "SearchX": SearchX,
  "Video": Video,
  "FolderOpen": FolderOpen,
  "Circle": Circle,
  "scan-face": ScanFace,
  "PackageCheck": PackageCheck,
  "list-ordered": ListOrdered,
  "Wallet": Wallet,
  "Files": Files,
  "CheckCheck": CheckCheck,
  "Database": Database,
  "Cookie": Cookie,
  "file-warning": FileWarning,
  "Layout": Layout,
  "user-minus": UserMinus,
  "file-spreadsheet": FileSpreadsheet,
  "help-circle": HelpCircle,
  "ImagePlus": ImagePlus,
  "ListOrdered": ListOrdered,
  "LineChart": LineChart,
  "Award": Award,
  "arrow-up-down": ArrowUpDown,
  "Weight": Weight,
  "heart-plus": HeartPlus,
  "CircleCheck": CircleCheck,
  "thumbs-up": ThumbsUp,
  "folder-search": FolderSearch,
  "HandCoins": HandCoins,
  "ScanFace": ScanFace,
  "DollarSign": DollarSign,
  "brain-circuit": BrainCircuit,
  "wallet-minimal": WalletMinimal,
  "area-chart": AreaChart,
  "LockKeyhole": LockKeyhole,
  "MessageCircleMore": MessageCircleMore,
  "Link2Off": Link2Off,
  "FileText": FileText,
  "BanknoteX": BanknoteX,
  "Droplets": Droplets,
  "Sliders": Sliders,
  "CloudCheck": CloudCheck,
  "x-octagon": XOctagon,
  "Euro": Euro,
  "PanelTop": PanelTop,
  "User": User,
  "arrow-right": ArrowRight,
  "list-plus": ListPlus,
  "AlertOctagon": AlertOctagon,
  "ArrowRightLeft": ArrowRightLeft,
  "Headset": Headset,
  "Twitter": Twitter,
  "Grid3x3": Grid3x3,
  "BookMarked": BookMarked,
  "user-x": UserX,
  "CalendarClock": CalendarClock,
  "flask-conical": FlaskConical,
  "ChartBar": ChartBar,
  "shopping-cart": ShoppingCart,
  "chevron-right": ChevronRight,
  "hard-hat": HardHat,
  "clipboard-check": ClipboardCheck,
  "Gauge": Gauge,
  "RadioTower": RadioTower,
  "circle-check": CircleCheck,
  "UserMinus": UserMinus,
  "ArrowRightCircle": ArrowRightCircle,
  "ThumbsDown": ThumbsDown,
  "external-link": ExternalLink,
  "filter-x": FilterX,
  "PowerOff": PowerOff,
  "CloudOff": CloudOff,
  "arrow-left": ArrowLeft,
  "Hash": Hash,
  "PlayCircle": PlayCircle,
  "Github": Github,
  "Network": Network,
  "ArrowUpSquare": ArrowUpSquare,
  "Dot": Dot,
  "Moon": Moon,
  "CircleAlert": CircleAlert,
  "Instagram": Instagram,
  "Images": Images,
  "check-circle2": CheckCircle2,
  "CalendarX": CalendarX,
  "arrow-down": ArrowDown,
  "Paperclip": Paperclip,
  "SlidersHorizontal": SlidersHorizontal,
  "Tag": Tag,
  "ArrowLeftRight": ArrowLeftRight,
  "Sprout": Sprout,
  "Inbox": Inbox,
  "FileQuestion": FileQuestion,
  "Split": Split,
  "loader-circle": LoaderCircle,
  "Scale": Scale,
  "ScanSearch": ScanSearch,
  "Cpu": Cpu,
  "CircleDot": CircleDot,
  "chart-line": ChartLine,
  "Pause": Pause,
  "Pencil": Pencil,
  "CircleDollarSign": CircleDollarSign,
  "Trophy": Trophy,
  "Vault": Vault,
  "Globe2": Globe2,
  "Calendar": Calendar,
  "Megaphone": Megaphone,
  "ToggleRight": ToggleRight,
  "AlarmClock": AlarmClock,
  "badge-alert": BadgeAlert,
  "scroll-text": ScrollText,
  "AlertTriangle": AlertTriangle,
  "Hand": Hand,
  "ArrowDownLeft": ArrowDownLeft,
  "Waypoints": Waypoints,
  "hand-coins": HandCoins,
  "line-chart": LineChart,
  "circle-alert": CircleAlert,
  "pie-chart": PieChart,
  "CircleSlash": CircleSlash,
  "Vote": Vote,
  "MessagesSquare": MessagesSquare,
  "SmartphoneCharging": SmartphoneCharging,
  "FilterX": FilterX,
  "message-square": MessageSquare,
  "Palette": Palette,
  "arrow-left-right": ArrowLeftRight,
  "Compass": Compass,
  "TrendingDown": TrendingDown,
  "GitBranch": GitBranch,
  "list-checks": ListChecks,
  "Bot": Bot,
  "plug-zap": PlugZap,
  "Unlink": Unlink,
  "Gift": Gift,
  "Undo2": Undo2,
  "Discord": Discord,
  "image-off": ImageOff,
  "minus-circle": MinusCircle,
  "chevrons-up-down": ChevronsUpDown,
  "ChevronUp": ChevronUp,
  "LayoutDashboard": LayoutDashboard,
  "clipboard-list": ClipboardList,
  "check-check": CheckCheck,
  "user-plus": UserPlus,
  "clock-alert": ClockAlert,
  "layout-dashboard": LayoutDashboard,
  "Building2": Building2,
  "alarm-clock": AlarmClock,
  "Facebook": Facebook,
  "smartphone-charging": SmartphoneCharging,
  "ThumbsUp": ThumbsUp,
  "Loader2": Loader2,
  "TrendingUp": TrendingUp,
  "FolderSearch": FolderSearch,
  "UsersRound": UsersRound,
  "Share2": Share2,
  "LockOpen": LockOpen,
  "ArrowUpFromLine": ArrowUpFromLine,
  "Activity": Activity,
  "ClockCheck": ClockCheck,
  "ShieldOff": ShieldOff,
  "Timer": Timer,
  "Landmark": Landmark,
  "Unplug": Unplug,
  "Gavel": Gavel,
  "messages-square": MessagesSquare,
  "TriangleAlert": TriangleAlert,
  "credit-card": CreditCard,
  "FilePlus": FilePlus,
  "ClipboardCheck": ClipboardCheck,
  "BrainCircuit": BrainCircuit,
  "key-round": KeyRound,
  "refresh-cw-off": RefreshCwOff,
  "FlaskConical": FlaskConical,
  "sliders-vertical": SlidersVertical,
  "ListCheck": ListCheck,
  "ArrowDownToLine": ArrowDownToLine,
  "refresh-cw": RefreshCw,
  "ScrollText": ScrollText,
  "Users": Users,
  "FileCode": FileCode,
  "ExternalLink": ExternalLink,
  "cloud-off": CloudOff,
  "Folders": Folders,
  "MoveHorizontal": MoveHorizontal,
  "MailCheck": MailCheck,
  "CirclePause": CirclePause,
  "LayoutGrid": LayoutGrid,
  "alarm-clock-off": AlarmClockOff,

  // Merged from the analytics KPI table this module replaced: names its
  // configs defend against that no source file happens to write today.
  "BarChart": BarChart,
  "bar-chart": BarChart,
  "bookmark": Bookmark,
  "CheckSquare": CheckSquare,
  "check-square": CheckSquare,
  "ChevronsDown": ChevronsDown,
  "chevrons-down": ChevronsDown,
  "ChevronsUp": ChevronsUp,
  "chevrons-up": ChevronsUp,
  "CloudUpload": CloudUpload,
  "cloud-upload": CloudUpload,
  "component": Component,
  "equal": Equal,
  "gem": Gem,
  "MailX": MailX,
  "mail-x": MailX,
  "MapPin": MapPin,
  "map-pin": MapPin,
  "MoreHorizontal": MoreHorizontal,
  "more-horizontal": MoreHorizontal,
  "phone": Phone,
  "PhoneIncoming": PhoneIncoming,
  "phone-incoming": PhoneIncoming,
  "PhoneOutgoing": PhoneOutgoing,
  "phone-outgoing": PhoneOutgoing,
  "server": Server,
  "shapes": Shapes,
  "ShieldBan": ShieldBan,
  "shield-ban": ShieldBan,
  "SquareCheck": SquareCheck,
  "square-check": SquareCheck,
  "triangle": Triangle,
  "UserCog": UserCog,
  "user-cog": UserCog,
  "XSquare": XSquare,
  "x-square": XSquare,
  "coin": Coins,
  "mdi:coin": Coins,
  "close": XCircle,
  "mdi:close": XCircle,
  "arrow-up-bold": ArrowUp,
  "mdi:arrow-up-bold": ArrowUp,
  "undo": Undo2,
  "mdi:undo": Undo2,
  "timer-sand-full": Hourglass,
  "mdi:timer-sand-full": Hourglass,
  "door-open": LockOpen,
  "mdi:door-open": LockOpen,
  "user-off": UserX,
  "mdi:user-off": UserX,
  "chat": MessageCircle,
  "mdi:chat": MessageCircle,
  "broadcast": Megaphone,
  "mdi:broadcast": Megaphone,
  "mdi:triangle": Triangle,
  "clock-time-four": Clock,
  "mdi:clock-time-four": Clock,
  "message-text": MessageSquare,
  "mdi:message-text": MessageSquare,
  "checkbox-marked-circle": CheckCircle2,
  "mdi:checkbox-marked-circle": CheckCircle2,
  "mdi:phone-incoming": PhoneIncoming,
  "hand-pointing-down": ThumbsDown,
  "mdi:hand-pointing-down": ThumbsDown,
  "cart-arrow-up": ArrowUpCircle,
  "mdi:cart-arrow-up": ArrowUpCircle,
  "bank-minus": Landmark,
  "mdi:bank-minus": Landmark,
  "grid": Grid3x3,
  "mdi:grid": Grid3x3,
  "storefront-outline": Store,
  "mdi:storefront-outline": Store,
  "mdi:cloud-upload": CloudUpload,
  "rocket-launch": Rocket,
  "mdi:rocket-launch": Rocket,
  "office-building": Building2,
  "mdi:office-building": Building2,
  "arrow-down-thick": ArrowDown,
  "mdi:arrow-down-thick": ArrowDown,
  "timer-cog": Settings,
  "mdi:timer-cog": Settings,
  "diamond": Gem,
  "mdi:diamond": Gem,
  "user-lock": Lock,
  "mdi:user-lock": Lock,
  "account-multiple-remove": UserMinus,
  "mdi:account-multiple-remove": UserMinus,
  "cart-outline": ShoppingCart,
  "mdi:cart-outline": ShoppingCart,
  "crown": Crown,
  "mdi:crown": Crown,
  "alert": AlertTriangle,
  "mdi:alert": AlertTriangle,
  "message-reply": MessageCircle,
  "mdi:message-reply": MessageCircle,
  "cart-arrow-down": ArrowDownCircle,
  "mdi:cart-arrow-down": ArrowDownCircle,
  "arrow-down-bold": ArrowDown,
  "mdi:arrow-down-bold": ArrowDown,
  "circle-double": CircleDot,
  "mdi:circle-double": CircleDot,
  "calendar-week": CalendarDays,
  "mdi:calendar-week": CalendarDays,
  "post-outline": FileText,
  "mdi:post-outline": FileText,
  "cart": ShoppingCart,
  "mdi:cart": ShoppingCart,
  "image-multiple": Images,
  "mdi:image-multiple": Images,
  "upload": Upload,
  "mdi:upload": Upload,
  "file-percent": Percent,
  "mdi:file-percent": Percent,
  "flask-outline": FlaskConical,
  "mdi:flask-outline": FlaskConical,
  "hand-pointing-up": ThumbsUp,
  "mdi:hand-pointing-up": ThumbsUp,
  "chevron-double-down": ChevronsDown,
  "mdi:chevron-double-down": ChevronsDown,
  "mdi:phone-outgoing": PhoneOutgoing,
  "post": FileText,
  "mdi:post": FileText,
  "polygon": Shapes,
  "mdi:polygon": Shapes,
  "certificate-outline": Award,
  "mdi:certificate-outline": Award,
  "check-bold": CheckCircle2,
  "mdi:check-bold": CheckCircle2,
  "dots-horizontal": MoreHorizontal,
  "mdi:dots-horizontal": MoreHorizontal,
  "earth": Globe,
  "mdi:earth": Globe,
  "cube": Box,
  "mdi:cube": Box,
  "arrow-split-vertical": Split,
  "mdi:arrow-split-vertical": Split,
  "store": Store,
  "mdi:store": Store,
  "mdi:equal": Equal,
  "chevron-double-up": ChevronsUp,
  "mdi:chevron-double-up": ChevronsUp,
  "checkbox-blank-circle-outline": Circle,
  "mdi:checkbox-blank-circle-outline": Circle,
  "arrow-up-thick": ArrowUp,
  "mdi:arrow-up-thick": ArrowUp,
  "user-remove": UserMinus,
  "mdi:user-remove": UserMinus,
  "tag-off": Tag,
  "mdi:tag-off": Tag,

  // A one-character name. The sweep that built this table used a >=2 char
  // pattern, so `lucide:x` (14 uses) was invisible to it AND to the gate.
  "lucide:x": X,
  "x": X,
  "X": X,

  // Prefixes the sweep never looked at. The scan that built this table filtered
  // on a list of known collection prefixes, and `material-symbols-light` was not
  // on it — so these two menu entries were skipped by the sweep AND passed by the
  // gate, and the P2P Exchange item shipped with a blank square. The gate no
  // longer allowlists prefixes; anything stored under an `icon` key must resolve.
  "material-symbols-light:p2p-outline": Handshake,
  "material-symbols-light:component-exchange": ArrowLeftRight,
};

/**
 * Weight/style suffixes that are a SET's vocabulary, not part of the concept:
 * Phosphor's `-duotone`, Solar's `-bold-duotone`, Material's `-outline`. A name
 * carrying one resolves to the same glyph as the name without it.
 */
const WEIGHT_SUFFIX =
  /-(?:outline|line|fill|filled|duotone|bold|solid|thin|light|regular|rounded|round|sharp|two-tone|variant)+$/;

/**
 * Resolve a stored icon name to a component.
 *
 * Tries, in order: the name verbatim; lowercased; with the set prefix dropped
 * (`mdi:magnify` -> `magnify`); and with trailing weight suffixes stripped
 * (`ph:gear-duotone` -> `gear`). Returns `undefined` when nothing matches — the
 * CALLER picks the fallback, because a menu wants a different stand-in than a
 * KPI tile does.
 *
 * Unlike the Iconify component this replaced, an unknown name cannot be fetched
 * into existence at runtime; it resolves to `undefined` and the caller's
 * fallback draws. That is the intended trade — `pnpm gate:icons` turns an
 * unresolvable name into a build failure rather than a blank space in prod.
 */
export function resolveIcon(name?: string | null): IconComponent | undefined {
  if (!name) return undefined;
  const raw = name.trim();
  if (!raw) return undefined;

  const direct = ICONS[raw];
  if (direct) return direct;

  const lower = raw.toLowerCase();
  if (ICONS[lower]) return ICONS[lower];

  const colon = lower.indexOf(":");
  const bare = colon >= 0 ? lower.slice(colon + 1) : lower;
  if (ICONS[bare]) return ICONS[bare];

  const stripped = bare.replace(WEIGHT_SUFFIX, "");
  return stripped !== bare ? ICONS[stripped] : undefined;
}

/** @returns true when `name` draws something. Used by the build gate. */
export function isKnownIcon(name?: string | null): boolean {
  return resolveIcon(name) !== undefined;
}

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, "ref"> {
  /** A stored icon name in any of the supported shapes. */
  icon?: string | null;
  size?: number | string;
  /** Drawn when `icon` does not resolve. Omit to render nothing. */
  fallback?: IconComponent;
}

/**
 * Drop-in replacement for `@iconify/react`'s `<Icon icon="…">` at the call
 * sites that resolve a name at RUNTIME — nav menus, payment rails, KPI configs
 * — where the name comes from a table and cannot become a static import.
 *
 * Call sites that know their glyph at author time should import it straight
 * from `lucide-react` instead: that tree-shakes to the one icon, while this
 * pulls the whole table.
 */
export function Icon({ icon, fallback, ...props }: IconProps) {
  const Resolved = resolveIcon(icon) ?? fallback;
  if (!Resolved) return null;
  return <Resolved {...props} />;
}

/**
 * The names a PICKER may offer — one per glyph, all guaranteed to draw.
 *
 * DERIVED FROM THE REGISTRY, NOT HAND-LISTED. The map above carries roughly
 * 1,300 keys for ~350 components: `lucide:wallet`, `mdi:wallet-outline`,
 * `wallet` and `Wallet` are four names for one picture. Offering all of them
 * would be a picker in which most choices are indistinguishable, and offering a
 * hand-kept subset would be a second list to keep in step with this one — the
 * exact failure `home-icons.test.ts` exists to catch elsewhere.
 *
 * The PascalCase keys are the canonical shape: `resolveIcon` matches them
 * verbatim, they are one-per-component by construction, and an object cannot
 * hold a duplicate. So an icon that exists here is offerable, and an icon
 * dropped from the map disappears from every picker on the next build rather
 * than becoming a stored name that renders nothing.
 */
export const ICON_NAMES: readonly string[] = Object.freeze(
  Object.keys(ICONS)
    .filter((key) => /^[A-Z][A-Za-z0-9]*$/.test(key))
    .sort((a, b) => a.localeCompare(b))
);
