/**
 * GENERATED by `frontend/scripts/vendor-fonts.mjs` — do not edit.
 *
 * The latin-subset file of each ALWAYS-PAINTED family. The root layout emits a
 * <link rel="preload"> for each, which is what next/font used to do for
 * families declared `preload: true`. The design manager's selectable families
 * are deliberately absent: they were `preload: false`, so only the one the
 * owner actually chose is ever fetched, and it is fetched when text renders.
 */
export const PRELOAD_FONTS = [
  "/fonts/caa3a2e1cccd8315-s.p.0wgildi0cnwt9.woff2",
  "/fonts/797e433ab948586e-s.p.0r6juujl39pe6.woff2",
  "/fonts/051742360c26797e-s.p.1bkzbscqrt8rl.woff2",
] as const;
