// Mapping between v5 products (extensions / ecosystem blockchains / exchange
// providers) and their MashDiv store listings (https://mashdiv.com/products).
//
// The animated art files in /public/img/store/*.svg are copies of the store's
// public/products/*.svg thumbnails (generated by store/scripts/
// generate-thumbnails.ts). They are self-contained animated SVGs — CSS
// keyframes run when loaded via <img>, and respect prefers-reduced-motion.
// Render them exactly like the store does: aspect-[5/3] + object-cover.

export const STORE_URL = "https://mashdiv.com";

/** extension.name (backend `extension` table) → store product slug */
export const EXTENSION_STORE_SLUGS: Record<string, string> = {
  ai_investment: "ai-investments",
  ai_support: "ai-support-agent",
  ecosystem: "ecosystem",
  forex: "forex",
  ico: "ico",
  staking: "staking",
  knowledge_base: "faq-system",
  ecommerce: "ecommerce",
  wallet_connect: "wallet-connect",
  p2p: "p2p",
  mlm: "mlm",
  mailwizard: "mailwizard-bicrypto",
  futures: "futures",
  nft: "nft-marketplace",
  ai_market_maker: "ai-market-maker",
  gateway: "payment-gateway",
  copy_trading: "copy-trading",
  chart_engine: "chart-engine",
  // These five use hand-authored thumbnails (not produced by the store's
  // generate-thumbnails.ts). The value is the SVG basename in /img/store/, which
  // is NOT the mashdiv.com listing slug — e.g. forex-trading.svg is listed as
  // "forex-multi-asset-trading". This map only drives art; the store link comes
  // from the DB `link` field, so never build a URL from these slugs.
  forex_trading: "forex-trading",
  binary_ai_engine: "binary-ai-engine",
  trading_bot: "trading-bot",
  hummingbot: "hummingbot",
  // Internal key `dex`, product name "Web3 Wallet & On-Chain Trading". Without
  // this entry the mega-menu art resolves to null — `storeArtForExtension` reads
  // only this map, and unlike the admin products page it has no
  // `extension.image` to fall back to.
  dex: "web3-wallet-trading",
};

/*
 * BUNDLED PRODUCTS HAVE ART TOO, and four of them had none.
 *
 * The maps below covered only what the MashDiv store lists. `binanceus`,
 * `kraken`, `okx` and the `MO` chain are rows the platform ships without
 * selling — they are not in `backend/seeders/20240402234748-exchanges.js` and
 * have no store listing — so `storeArtForProduct` returned null and each one
 * rendered on `/admin/system/extension` as a bare category icon beside seven
 * siblings that had full illustrations.
 *
 * Their art is generated by `scripts/generate-store-art.mjs` from the same
 * templates, so it is the same grammar rather than a lookalike. The slug is NOT
 * a mashdiv.com listing slug for these four — nothing may build a store URL
 * from them, which is already the rule the extension map records above.
 */

/** ecosystemBlockchain.chain → store product slug */
export const BLOCKCHAIN_STORE_SLUGS: Record<string, string> = {
  SOL: "solana",
  TRON: "tron",
  XMR: "monero",
  TON: "ton",
  MO: "mo-chain",
};

/** exchange.name → store product slug */
export const EXCHANGE_STORE_SLUGS: Record<string, string> = {
  binance: "binance-provider",
  binanceus: "binanceus-provider",
  kraken: "kraken-provider",
  kucoin: "kucoin-provider",
  okx: "okx-provider",
  xt: "xt-provider",
  bybit: "bybit-provider",
  mexc: "mexc-provider",
  gate: "gate-provider",
  bitget: "bitget-provider",
  coinbase: "coinbase-provider",
  htx: "htx-provider",
  upbit: "upbit-provider",
  cryptocom: "cryptocom-provider",
  bitfinex: "bitfinex-provider",
  lbank: "lbank-provider",
};

export function storeProductUrl(slug: string): string {
  return `${STORE_URL}/products/${slug}`;
}

export function storeArt(slug: string): string {
  return `/img/store/${slug}.svg`;
}

/** Animated store art for a mega-menu item's `extension` name, if we have it. */
export function storeArtForExtension(
  extensionName?: string | null
): string | null {
  if (!extensionName) return null;
  const slug = EXTENSION_STORE_SLUGS[extensionName];
  return slug ? storeArt(slug) : null;
}

/**
 * Animated store art for an admin products-page entry
 * (extension / blockchain / exchange), if we have it.
 */
export function storeArtForProduct(product: {
  category?: string;
  name?: string;
  chain?: string;
}): string | null {
  let slug: string | undefined;
  if (product.category === "blockchain") {
    slug = product.chain ? BLOCKCHAIN_STORE_SLUGS[product.chain] : undefined;
  } else if (product.category === "exchange") {
    slug = product.name
      ? EXCHANGE_STORE_SLUGS[product.name.toLowerCase()]
      : undefined;
  } else {
    slug = product.name ? EXTENSION_STORE_SLUGS[product.name] : undefined;
  }
  return slug ? storeArt(slug) : null;
}
